# Configuration file for Arrikto Rok JupyterHub Spawner UI
# Each key corresponds to JupyterHub Rok Spawner UI option

# The structure of this file is very similar with the one of the default
# Spawner UI configuration, available at:
#
# kubeflow/jupyter/ui/default/config.yaml

spawnerFormDefaults:
  rokLabURL:
    # The URL of a Jupyter Lab, already snapshotted in Rok
    value: ''
  image:
    # The container Image for the user's Jupyter Notebook
    # If readonly, this value must be a member of the list below
    value: gcr.io/anomaly-detection-jupyter/tensorflow-1.12.0-notebook-cpu:latest
    # The list of available standard container Images
    options:
      - gcr.io/anomaly-detection-jupyter/tensorflow-1.12.0-notebook-cpu:latest
    # By default, custom container Images are allowed
    # Uncomment the following line to only enable standard container Images
    readOnly: true
  cpu:
    value: '1.0'
  memory:
    value: 1.0Gi
  workspaceVolume:
    # Each Workspace Volume is declared with the following attributes:
    # Type, RokURL, Name, Size and MountPath
    value:
      type:
        value: New
      rokURL:
        value: ''
      name:
        value: {username}{servername}-workspace
      size:
        value: '10'
      mountPath:
        readOnly: true
        value: /home/jovyan
  dataVolumes:
    value: []
    # Each Data Volume is declared with the following attributes:
    # Type, RokURL, Name, Size and MountPath
    #
    # For example, a list with a single Data Volume
    #value:
    #  - value:
    #      type:
    #        value: New
    #      rokURL:
    #        value: ''
    #      name:
    #        value: {username}{servername}-vol-1
    #      size:
    #        value: '10'
    #      mountPath:
    #        value: /home/jovyan/{username}{servername}-vol-1
    #
    # Uncomment the following line to make the Data Volumes list readonly
    #readOnly: true
  extraResources:
    value: "{{}}"
